export const SEARCH_DATA = "SEARCH_DATA";
export const FETCH_DATA_START = "FETCH_DATA_START";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILED = "FETCH_DATA_FAILED";
export const GET_NEXT_LIST = "GET_NEXT_LIST";
export const GET_PREV_LIST = "GET_PREV_LIST";

export const SELECTED_MUSIC = "SELECTED_MUSIC";

export const UPDATE_PLAYER = "UPDATE_PLAYER";


export const GET_ALBUM_TRACKS_START = "GET_ALBUM_TRACKS_START";
export const GET_ALBUM_TRACKS_SUCCESS = "GET_ALBUM_TRACKS_SUCCESS";
export const GET_ALBUM_TRACKS_FAILED = "GET_ALBUM_TRACKS_FAILED"; 
export const VIEW_ALBUM_DETAILS = "VIEW_ALBUM_DETAILS";



export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SEARCH_BAR_UI_SHOW = 'SEARCH_BAR_UI_SHOW';
export const SEARCH_BAR_UI_HIDE = 'SEARCH_BAR_UI_HIDE';

export const SAVE_ALBUM_START = 'SAVE_ALBUM_START';
export const SAVE_ALBUM_SUCCESS = 'SAVE_ALBUM_SUCCESS';
export const SAVE_ALBUM_FAILED = 'SAVE_ALBUM_FAILED';


export const FETCH_ALBUMS_START = 'FETCH_ALBUM_START';
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUM_SUCCESS';
export const FETCH_ALBUMS_FAILED = 'FETCH_ALBUM_FAILED'

