export const SEARCH_DATA = "SEARCH_DATA";
export const FETCH_DATA = "FETCH_DATA";
export const FETCH_DATA_FAILED = "FETCH_DATA_FAILED";

export const SELECTED_MUSIC = "SELECTED_MUSIC";

export const UPDATE_PLAYER = "UPDATE_PLAYER";
