export const SEARCH_DATA = "SEARCH_DATA";
export const FETCH_DATA = "FETCH_DATA";
export const FETCH_DATA_FAILED = "FETCH_DATA_FAILED";
export const GET_NEXT_LIST = "GET_NEXT_LIST";
export const GET_PREV_LIST = "GET_PREV_LIST";

export const SELECTED_MUSIC = "SELECTED_MUSIC";

export const UPDATE_PLAYER = "UPDATE_PLAYER";


export const GET_ALBUM_TRACKS = "GET_ALBUM_TRACKS";
export const GET_ALBUM_TRACKS_FAILED = "GET_ALBUM_TRACKS_FAILED"; 

